### ISSUE TITLE
Can't install because princexml.com is down

### ISSUE THREAD

**Issue by pbrackenjci** [rse/node-prince#44]
I can't install this module because princexml.com is down for the past few hours. Why aren't the binaries either included in the node module or downloaded from a resilient CDN?

**Comment by rse** [comment]
Because one cannot embed such a lot of data into an NPM module (NPM went havoc in the past on such embeddings) and AFAIK there is no CDN used by PrinceXML. When you know a CDN, I can add support for it in the NPM module, of course. But until the CDN is available for PrinceXML I cannot do anything here AFAIK.
